### ISSUE TITLE
Program fails to run on Python 3.10

### ISSUE THREAD

**Issue by NorbertLindenberg** [lantip/sawa#10]
(sawa) $ ꦱꦮ ꦱꦪ.ꦱꦮ
[-] ꦱꦮ mbutuhaké Python vèrsi 3.6 munggah.
(sawa) $ python --version
Python 3.10.4

**Comment by lantip** [comment]
Thank you very much.
I've already fixed the issue, please pip upgrade to the latest version.

**Comment by NorbertLindenberg** [comment]
Thank you – the fix works.
