### ISSUE TITLE
rekomendasi font aksara jawa

### ISSUE THREAD

**Issue by lakuapik** [lantip/sawa#4]
apakah ada rekomendasi font aksara jawa yang bagus untuk memulai koding dengan sawa?

suwun.

**Comment by lantip** [comment]
sebenarnya hampir semua font sudah bagus sekarang mas, yang agak bermasalah cuma google noto sans javanese v1 yang semacam terpotong kakinya satu. 

tapi kalau mau pilihan lain, bisa ke [aksaradinusantara](https://aksaradinusantara.com/fonta/aksara/jawa) ada banyak pilihan.

kalau maksud pertanyaannya font yang fixed-width, sependek yang saya tahu belum ada kecuali font bata (istaka) karya mas bayu. ada juga di list font di situs di atas.
