### ISSUE TITLE
sawa in windows

### ISSUE THREAD

**Issue by cpamungkas** [lantip/sawa#5]
mas, aq nyoba instal di windows 
pip instal sawa sukses tersimpan di Lib->site-packages->sawa
tp pas mau cb sample 1 script print di command prompt function prin ndak dikenali
trus nampaknya command prompt windows ga kenal aksara jawa,, krna pakai pycharm, jupyter notebook semua bisa mbaca aksara jawa..error nya hanya python ndak bisa baca fungsi..

apa ada lokasi yg perlu diperbaiki biar python mbaca fungsi dr sawa.

![image](https://user-images.githubusercontent.com/1875521/121365352-c5f3cf80-c962-11eb-925b-b0a20194b785.png)

sedangkan di pycharm kudu begini 

![image](https://user-images.githubusercontent.com/1875521/121365470-e15eda80-c962-11eb-84cc-c510e1d56d13.png)

kira2 knp ya?

**Comment by lantip** [comment]
oh sepertinya ada perbedaan di executable di windows. 

terimakasih masukannya mase, saya coba riset dulu 😄

**Comment by cpamungkas** [comment]
siap mas'e,,

**Comment by lantip** [comment]
Sudah saya perbaiki mas, 
permasalahannya di system windows yang memang tidak secara default merender utf-8. 
Untuk masalah tampilan di command prompt, saya juga belum berhasil. Tapi kalau googling sepertinya ada saran untuk itu. Nanti saya tambahkan di readme mengenai itu kalau sudah ketemu.

Untuk permasalahan njenengan di atas, saya bisa menjalankan dengan langkah begini mas:

Jalankan command prompt dengan administrator privilege. Caranya: search cmd, ctrl+shift+enter

1. Install virtualenv
   `C:\Users\nama\python -m venv C:\Users\nama\venv`
2. Active-kan virtualenv
   `C:\Users\nama\C:\Users\nama\venv\Scripts\activate.bat`
3. Install sawa terbaru (versi 1.0.2). Uninstall dulu yang sebelumnya dengan `pip uninstall sawa`
   `(venv)C:\Users\sawa\pip install sawa==1.0.2`
4. Jalankan sawa dengan mengetik ꦱꦮ karena perintahnya memang saya bikin harus pakai aksara jawa. Saya juga belum bisa mengetik langsung tadi, sehingga saya pakai kopi paste. 

<img width="786" alt="Screen Shot 2021-06-09 at 23 53 37" src="https://user-images.githubusercontent.com/3334064/121397715-cb5f1300-c97e-11eb-8cab-9d7d1240736d.png">


Silakan dicoba mas. Semoga bisa dijalankan.

**Comment by cpamungkas** [comment]
sukses mas..

![image](https://user-images.githubusercontent.com/1875521/121557601-12acd880-ca3f-11eb-8de6-064acc52788a.png)

maturnuwun sanget nggih..

**Comment by lantip** [comment]
siap! sami-sami! :D
